AWSTemplateFormatVersion: '2010-09-09'
Resources:

  # ====================== Lambda Function for StateMachineInit

  StateMachineInitLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-stateMachineInitLambda
      Handler: index.handler
      Role: !GetAtt StateMachineInitLambdaRole.Arn
      Code:
        S3Bucket: !ImportValue LambdaCodeBucketName
        S3Key: stateMachineInitLambda.zip
      Environment:
        Variables:
          BATCH_TABLE: !Ref BatchTable
          REQUEST_TABLE: !Ref RequestTable
          STATE_MACHINE_ARN: !Ref StateMachine
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 60

  StateMachineInitLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref StateMachineInitLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/*/stateMachineInit

  ProcessTask1Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-processTask1Lambda
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !ImportValue LambdaCodeBucketName
        S3Key: processTask1Lambda.zip
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 60

  ProcessTask2Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-processTask2Lambda
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !ImportValue LambdaCodeBucketName
        S3Key: processTask2Lambda.zip
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 60

  UpdateBatchLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-updateBatchLambda
      Handler: index.handler
      Role: !GetAtt UpdateBatchLambdaRole.Arn
      Code:
        S3Bucket: !ImportValue LambdaCodeBucketName
        S3Key: updateBatchLambda.zip
      Runtime: nodejs20.x
      Environment:
        Variables:
          BATCH_TABLE: !Ref BatchTable
          REQUEST_TABLE: !Ref RequestTable
      MemorySize: 128
      Timeout: 60

  # ====================== API Gateway
  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: LambdaApi

  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: prod
      RestApiId: !Ref ApiGatewayRestApi
      DeploymentId: !Ref ApiGatewayDeployment
      MethodSettings:
        - DataTraceEnabled: true
          HttpMethod: "*"
          ResourcePath: "/*"
          LoggingLevel: INFO
          MetricsEnabled: true
  
  ApiGatewayAccount:
    Type: 'AWS::ApiGateway::Account'
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - ApiGatewayCloudWatchRole
          - Arn

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - StateMachineInitApiMethod
      - StateMachineInitOptionsMethod
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      StageName: dummyStage
  
  StateMachineInitApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: stateMachineInit
      RestApiId: !Ref ApiGatewayRestApi
  
  StateMachineInitApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Ref StateMachineInitApiResource
      RestApiId: !Ref ApiGatewayRestApi
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: 
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StateMachineInitLambda.Arn}/invocations

  StateMachineInitOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: OPTIONS
      ResourceId: !Ref StateMachineInitApiResource
      RestApiId: !Ref ApiGatewayRestApi
      Integration:
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
            ResponseTemplates:
              application/json: '{"statusCode": 200}'
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: "'*'"
            method.response.header.Access-Control-Allow-Headers: "'Content-Type'"
            method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"


  # ====================== DynamoDB
  BatchTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: 'BatchTable'
      AttributeDefinitions: 
        - AttributeName: 'batchId'
          AttributeType: 'S'
        - AttributeName: 'status'
          AttributeType: 'S'
        - AttributeName: 'timestamp'
          AttributeType: 'N'
      KeySchema: 
        - AttributeName: 'batchId'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: 'StatusIndex'
          KeySchema:
            - AttributeName: 'status'
              KeyType: 'HASH'
            - AttributeName: 'timestamp'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: 'ALL'

  RequestTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'RequestTable'
      AttributeDefinitions:
        - AttributeName: 'requestId'
          AttributeType: 'S'
        - AttributeName: 'batchId'
          AttributeType: 'S'
        - AttributeName: 'itemId'
          AttributeType: 'S'
        - AttributeName: 'status'
          AttributeType: 'S'
        - AttributeName: 'timestamp'
          AttributeType: 'N'
      KeySchema:
        - AttributeName: 'requestId'
          KeyType: 'HASH'
        - AttributeName: 'itemId'
          KeyType: 'RANGE'
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: 'BatchIdIndex'
          KeySchema:
            - AttributeName: 'batchId'
              KeyType: 'HASH'
            - AttributeName: 'timestamp'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: 'ALL'
        - IndexName: 'ItemIdStatusIndex'
          KeySchema:
            - AttributeName: 'itemId'
              KeyType: 'HASH'
            - AttributeName: 'status'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: 'ALL'

  # ====================== StepFunctions
  IntegrationStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/vendedlogs/states/integrationStateMachine-Logs"

  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: integrationStateMachine
      StateMachineType: EXPRESS
      LoggingConfiguration:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt IntegrationStateMachineLogGroup.Arn
      RoleArn: !GetAtt StepFunctionsExecutionRole.Arn
      DefinitionString: !Sub |
        {
          "Comment": "State machine for process tasks",
          "StartAt": "ProcessTask1",
          "States": {
            "ProcessTask1": {
              "Type": "Task",
              "Resource": "${ProcessTask1Lambda.Arn}",
              "Next": "ProcessTask2"
            },
            "ProcessTask2": {
              "Type": "Task",
              "Resource": "${ProcessTask2Lambda.Arn}",
              "Next": "UpdateBatch"
            },
            "UpdateBatch": {
              "Type": "Task",
              "Resource": "${UpdateBatchLambda.Arn}",
              "End": true
            }
          }
        }

  # ====================== IAM Roles

  StateMachineInitLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: StateMachineInitLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref StateMachine
              - Effect: Allow
                Action:
                  - dynamodb:ListTables
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:ConditionCheckItem
                  - dynamodb:PutItem
                  - dynamodb:DescribeTable
                  - dynamodb:GetItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                Resource: 
                  - !GetAtt BatchTable.Arn
                  - !GetAtt RequestTable.Arn

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  UpdateBatchLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: UpdateBatchPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:ListTables
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:ConditionCheckItem
                  - dynamodb:PutItem
                  - dynamodb:DescribeTable
                  - dynamodb:GetItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                Resource: 
                  - !GetAtt BatchTable.Arn
                  - !GetAtt RequestTable.Arn
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/BatchTable/index/StatusIndex"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/RequestTable/index/BatchIdIndex"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/RequestTable/index/ProductStatusIndex"

  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionsExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt ProcessTask1Lambda.Arn
                  - !GetAtt ProcessTask2Lambda.Arn
                  - !GetAtt UpdateBatchLambda.Arn
        - PolicyName: CloudWatchLogsFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - cloudwatch:GenerateQuery
                Resource: "*"

  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies: 
        - PolicyName: "ApiGatewayLoggingPolicy"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action: 
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:DescribeLogGroups"
                  - "logs:DescribeLogStreams"
                  - "logs:PutLogEvents"
                  - "logs:GetLogEvents"
                  - "logs:FilterLogEvents"
                Resource: 
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/apigateway/*"

Outputs:
  StackName:
    Description: StackName
    Value: !Ref AWS::StackName
  ApiUrl:
    Description: "URL del API Gateway"
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
